export const data = {
  'AUSLBO - Dipartimento Cure Primarie': {
    uo: [
      'CONSULTORI FAMILIARI',
      'PEDIATRIA TERRITORIALE',
      "ALTRE SPECIALITA'",
      'MIGRANTI E BASSA SOGLIA',
      'CARCERE',
      'GERIATRIA TERRITORIALE',
      'RETE CURE PALLIATIVE ADULTO (RCPA)',
    ],
    structurePavilionAddress: [
      'POL. ZANOLINI, Via Antonio Zanolini 2 - Bologna',
      'CDC NAVILE, Via Domenico Svampa 8 - Bologna',
      'CDC BORGO RENO, Via Ercole Nani 10 - Bologna',
      'POL. RENO VIA COLOMBI, Via Arturo Colombi 3 - Bologna',
      'POL. CARPACCIO, Via Vittore Carpaccio 2 - Bologna',
      'Centro Salute Donne Straniere c/o CDC S.VITALE-S.DONATO, Via Filippo Beroaldo 4/2 - Bologna',
      'CDC S.VITALE-S.DONATO, Via Filippo Beroaldo 4/2 - Bologna',
      'POL. MAZZACORATI, Via Toscana 17/19 - Bologna',
      'CDC PORTO-SARAGOZZA, Via S. Isaia 94/a - Bologna (accesso da S. Isaia 90)',
      'CENTRO C.A.S.A., Via S. Isaia 90 - Bologna (1° piano)',
      'POL. PILASTRO, Via Luigi Pirandello 8 - Bologna',
      'POL. MENGOLI, Via Pietro Mengoli 32 - Bologna',
      'POL. BYRON, Via George Byron 30 - Bologna',
      'POL. MONTEBELLO, Via Montebello 6 - Bologna',
      'Casa di Cura Villa Nigrisoli (Osp. Accr), Viale G. Ercolani 9 - Bologna',
      'CDC CASALECCHIO DI RENO, Piazzale Rita Levi Montalcini 5 - Casalecchio di Reno (BO)',
      'CDC SASSO MARCONI, Via Guido Bertacchi 11 - Sasso Marconi (BO)',
      'POL. VALSAMOGGIA c/o Ospedale Don G. Dossetti, Viale dei Martiri 10/A - Bazzano (frazione di Valsamoggia) (BO)',
      'CDC LAVINO SAMOGGIA, Piazza Giuseppe di Vittorio 1 - Zola Predosa',
      'CDC S. LAZZARO DI SAVENA, Via della Repubblica 11 - San Lazzaro di Savena (BO)',
      "CDC OZZANO, Viale Giovanni XXIII n. 29 - Ozzano dell'Emilia (BO)",
      'POL. PIANORO, Via Risorgimento 8 - Pianoro (BO)',
      'CDC "PATRIZIA CARPANI", Via Roma 8 - Loiano (BO)',
      'POL. MONGHIDORO, Piazza Giacomo Matteotti 1 - Monghidoro (BO)',
      'Distretto Pianura Est - S.GIOVANNI IN PERSICETO, Via Marzocchi 2 - San Giovanni in Persiceto (BO)',
      "POL. ANZOLA, Via XXV Aprile n. 9 - Anzola dell'Emilia (BO)",
      'CDC "MARIA MONTESSORI", Via 1° Maggio n. 15 - Calderara di Reno (BO)',
      'CDC DELLE TERRE D\'ACQUA "BARBERINI", Viale Libertà 171 - Crevalcore (BO)',
      'CDC SALA BOLOGNESE, Via Giotto 2 - Sala Bolognese (BO)',
      'POL. BARICELLA, Via Europa 15 - Baricella (BO)',
      'CDC BUDRIO, Via Benni 44 - Budrio (BO)',
      'POL. CASTEL MAGGIORE, Piazza 2 Agosto 1980 n. 2 - Castel Maggiore (BO)',
      "POL. GRANAROLO DELL'EMILIA, Via San Donato 74 - Granarolo dell'Emilia (BO)",
      'POL. MOLINELLA, Via Provinciale Circonvallazione 47 - Molinella (BO)',
      'CDC S. PIETRO IN CASALE-GALLIERA, Via Asia 61 - San Pietro in Casale (BO)',
      'CDC PIEVE di CENTO, Via Luigi Campanini 4 - Pieve di Cento (BO)',
      'POL. CASTENASO, Via Marconi 16 - Castenaso (BO)',
      'CDC PORRETTA, Via Oreste Zagnoni 5 - Porretta Terme (BO)',
      "CDC VERGATO, Via dell'Ospedale 1 - Vergato (BO)",
      'POL. VERGATO, Via Fornaci 343/G - Vergato',
      'POL. S. BENEDETTO VAL DI SAMBRO, Via della Resistenza 2/1 - San Benedetto Val di Sambro (BO)',
      'CDC CASTIGLIONE DEI PEPOLI, Via Sensi, 12 - Castiglione dei Pepoli (BO)',
      'CASA DELLA COMUNITÀ VADO, Via Val di Setta 4/A - Vado (BO)',
      'A DOMICILIO DEL PAZIENTE',
    ],
  },

  'AUSLBO - Dipartimento Salute Mentale- Dipartimento Dipendenze patologiche': {
    uo: [
      'Day Service Bologna, Ospedale Maggiore (edificio C) Largo Nigrisoli, 2',
      "Centro Diurno per preadolescenti e adolescenti ;Bologna, Via dell'Osservanza, 23",
      'Bologna,',
      'CSM Savena - S. Stefano ; Bologna,  Via Toscana, 17/19',
      'CSM San Donato - San Vitale ; Bologna, Via Zanolini, 2',
      'SPDC Malpighi c/o S.Orsola-Malpighi Padiglione Pelagi ; Bologna, Via Pelagio Palagi, 9',
      'CSM Borgo Reno ,Bologna, Via Nani, 10',
      'CSM Navile ,Bologna, Via Svampa, 8',
      'CSM Saragozza ,Bologna, Viale Carlo Pepoli, 5',
      'RTI Arcipelato ,Bologna, Viale Carlo Pepoli, 5',
      'CSM San Pietro in Casale ,San Pietro in Casale ,Via Asia, 61',
      'Ambulatorio Baricella, Via Europa, 15',
      'Ambulatorio Castelmaggiore, P.zza 2 Agosto 1980, 2',
      'Ambulatorio Pieve di Cento, Via L. Campanili, 4',
      'CSM Budrio, Via Benni, 44',
      'Ambulatorio Castenaso, Via Marconi, 16',
      "Ambulatorio Granarolo dell'Emilia, Via S. Donato, 74a",
      'Ambulatorio Molinella, Via Circonvallazione, 47',
      'CSM Pianura Ovest, San Giovanni in Persiceto, Via Marzocchi, 3',
      'Ambulatorio Crevalcore, Viale Libertà, 171',
      'Ambulatorio S. Agata Bolognese, Via Sibirani, 5',
      'Ambulatorio Calderara di Reno, Via 1° Maggio, 15',
      "Ambulatorio Anzola dell'Emilia, Via XXV aprile, 15",
      'SPDC San Giovanni in Persiceto c/ Ospedale San GiovanniSan Giovanni in Persiceto, Via Marzocchi, 2',
      'CSM Reno Lavino Samoggia, Casalecchio di Reno, Via Cimarosa, 5/2',
      'Ambulatorio Bazzano, Via dei Martiri, 10/a',
      'Ambulatorio Zola Predosa, P.zza di Vittorio, 1',
      'CSM Appennino Bolognese, Vergato, Via Fornaci, 343/G',
      'Ambulatorio Castiglione dei Pepoli, Via Sensi, 12/14',
      'Ambulatorio Porretta Terme, Via Zagnoni, 3-5',
      'Ambulatorio Vado di Monzuno, Via Val di Setta, 4/A',
      'CSM Savena Idice, San Lazzaro di Savena, Via del Seminario, 1',
      'Ambulatorio Loiano, Via Roma, 8',
      'Ambulatorio Monghidoro, Via Matteotti, 1',
      "Ambulatorio Ozzano dell'Emilia, Via Giovanni XXIII, 29",
      'Ambulatorio Pianoro, Viale Risorgimento, 8',
      "SPDC Maggiore c/o Ospedale Maggiore C.A. Pizzardi ;Bologna; Via dell'Ospedale 1",
      'RTR-E Casa degli Svizzeri ;Bologna; Via Terracini, 33',
      'Casa Circondariale Dozza ;Bologna; Via del Gomito, 2',
      'SerDP Bologna Est ;Bologna; Via Carpaccio, 2',
      'SerDP Bologna Ovest c/o Ospedale Maggiore Edificio A ;Bologna; Largo Nigrisoli, 2',
      'SerDP Navile ;Bologna; Via Fioravanti, 10',
      'SerDP Pepoli ;Bologna; Viale Carlo Pepoli, 3/5',
      'SerDP Pianura - Budrio ;BudrioVia Benni,44',
      'SerDP Pianura - San Giorgio ;San Giorgio di Piano, Via Carducci, 24',
      'SerDP Pianura - San Giovanni ;San Giovanni in Persiceto, Via Marzocchi, 1',
      'SerDP Sud - Zola ;Zola Predosa, P.zza di Vittorio, 1',
      'SerDP Sud - Vergato ; Via Fornaci, 343/G',
      'SerDP Sud - San Lazzaro ;San Lazzaro di Savena, Via Repubblica, 11',
      'Poliambulatorio Zanolini ;Bologna, Via Zanolini, 2',
      'Poliambulatorio Mazzacorati  ;Bologna, Via Toscana, 17/19',
      'Poliambulatorio Carpaccio ;Bologna, Via Carpaccio, 2',
      'Poliambulatorio Pilastro ;Bologna, Via Pirandello, 6/8',
      'Casa della Comunità Porto Saragozza ;Bologna, Via S. Isaia, 90',
      'Casa della Comunità Navile ;Bologna, Via Svampa, 8',
      'Casa della Comunità Borgo Reno ;Bologna, Via Nani, 10',
      'Poliambulatorio ;Bologna, Via Colombi, 3',
      'Casa della Comunità Budrio, Budrio, Via Benni, 44',
      'Poliambulatorio Castenaso, Castenaso, Via Marzconi, 16',
      "Poliambulatorio Granarolo, Granarolo dell'EmiliaVia S. Donato, 74a",
      'Polo Sanitario,Molinella, Via Circonvallazione, 47',
      'Poliambulatorio San Giorgio, San Giorgio di Piano, Via Pirotti, 22',
      'Poliambulatorio Baricella, Baricella, Via Europa, 15',
      'Poliambulatorio Castelmaggiore, Castelmaggiore, Piazza 2 Agosto, 2',
      'Polo Sanitario,San Pietro in Casale, Via Asia, 61',
      'Ambulatorio San Giovanni in Persiceto, Via Marzocchi, 2',
      'Poliambulatorio Maria Montessori, Calderara di Reno, Via I maggio, 15',
      'Casa della Comunità delle Terre d\'Acqua "Barberini", Crevalcore, Viale Libertà, 171',
      'Casa della Comunità Casalecchio di Reno, Casalecchio di Reno, Piazzale R.L. Montalcini,5',
      'Poliambulatorio Bazzano, Bazzano, Via dei Martiri, 10a',
      'Casa della Comunità Reno Sasso, Sasso Marconi, Via Bertacchi, 11',
      'Casa della Comunità Lavino Samoggia, Zola Predosa, Piazza G. di Vittorio, 1',
      'Casa della Comunità Alto Reno Terme c/o Ospedale Civile Costa, Porretta Terme, Via Zagnoni, 3-5',
      'Casa della Comunità Castiglione dei Pepoli, Castiglione dei Pepoli, Via Sensi, 12',
      'Casa della Comunità Vado-Monzuno, Vado di Monzuno, Via Val di Setta, 4/A',
      "Casa della Comunità Vergato, Vergato, Via dell'Ospedale, 1",
      'Casa della Comunità Loiano, Loiano, Via Roma, 8',
      'Poliambulatorio San Camillo, San Lazzaro di Savena, Via del Seminario, 1',
      'Poliambulatorio Pianoro, Pianoro, Via Risorgimento, 8',
      "Casa della Comunità Ozzano dell'Emilia, Ozzano dell'Emilia, Viale Giovanni XXIII, 29",
      'Dipartimento di Psicologia, Servizio di Consulenza Psicologica in ambito giuridico',
    ],
    structurePavilionAddress: [
      'UOC',
      "UO SSD PSICHIATRIA E PSICOTERAPIA ETA' EVOLUTIVA",
      'UOC PSICHIATRIA BOLOGNA EST',
      'UOC PSICHIATRIA BOLOGNA OVEST',
      'UOC PSICHIATRIA PIANURA',
      'UOC PSICHIATRIA SUD',
      'UOC DIAGNOSI E CURA MAGGIORE',
      'UOC PSICHIATRIA FORENSE',
      'UOC DIPENDENZE PATOLOGICHE',
      'UOC NPIA BOLOGNA EST',
      'UOC NPIA BOLOGNA OVEST',
      'UOC NPIA PIANURA',
      'UOC NPIA SUD',
      "UNIVERSITA' DI BOLOGNA",
    ],
  },

  'IRCCS Istituto delle Neuroscienze': {
    uo: [
      'Ospedale Bellaria, Via Altura 3, Bologna',
      'Ospedale Maggiore, Largo Bartolo Nigrisoli 2, Bologna',
      'Ospedale Bellaria e Azienda Ospedaliero-Universitaria di Bologna',
      'Azienda Ospedaliero-Universitaria di Bologna',
    ],
    structurePavilionAddress: [
      'UOC Clinica Neurologica',
      'UOC Disturbi dello Spettro Autistico',
      'UOC Neurologia OB',
      'UOC Oncologia del Sistema Nervoso',
      'UOSI Riabilitazione Sclerosi Multipla',
      'UOC Neuroriabilitazione',
      'UOC Neurochirurgia',
      'UOC Anestesia e Rianimazione OB',
      'UOC Neuroradiologia',
      'UOC Medicina Riabilitativa Infantile',
      "UO Governo dei percorsi clinico assistenziali d'Istituto",
      'Direzione Scientifica',
      'Direzione Operativa',
      'Direzione Sanitaria IRCCS',
      'Direzione Amministrativa IRCCS',
      'Programma Neurochirurgia Vertebrale',
      'Programma Neuroimmagini funzionali e molecolari',
      'Programma Neuroradiologia con tecniche ad elevata complessità',
      'Programma Epilessia',
      'Programma Neurochirurgia Ipofisi',
      'Programma Disturbi del Comportamento Alimentare',
      "Programma Neurochirurgia Vascolare e d'Urgenza e Neurotraumatologia",
      'Programma Cefalee ed Algie Facciali',
      'Programma terapie innovative nei disordini del movimento e vegetativo',
      "Programma Patologia neuromuscolare dell'adulto e neuroimmunologia",
      'UOC Neurologia OM e Rete Stroke Metropolitana',
      'UOC Neuroradiologia OM',
      'UOC Clinica Neurologica - Rete Neurologica Metropolitana (NeuroMet)',
      "UOC Neuropsichiatria dell'Età Pediatrica",
      'Programma Neurochirurgia Pediatrica',
      'UOC Neurologia AOU',
    ],
  },

  'AUSLBO - Dipartimento di Sanità pubblica': {
    structurePavilionAddress: [
      'DIREZIONE DSP, San Lazzaro di Savena, Via Seminario, 1',
      'PROGRAMMA AMBIENTE E SALUTE, Bologna, Via Montebello 6',
      'PROGRAMMA AMBIENTE E SALUTE, San Lazzaro di Savena, Via Seminario, 1',
      'PROGRAMMA AMBIENTE E SALUTE, San Giovanni in Persiceto, Circonvallazione Dante, 12d',
      "PROGRAMMA PROMOZIONE SALUTE E PROMOZIONE CRONICITA', Bologna, Via Montebello 6",
      "PROGRAMMA PROMOZIONE SALUTE E PROMOZIONE CRONICITA', San Lazzaro di Savena, Via Seminario, 1",
      'U.O. MEDICINA DELLO SPORT (SSD), Bologna, Via Colombi, 3',
      'U.O. MEDICINA DELLO SPORT (SSD), Bologna, Via Mengoli, 32',
      'U.O. MEDICINA DELLO SPORT (SSD), San Lazzaro di Savena, Via della Repubblica, 11',
      'U.O. MEDICINA DELLO SPORT (SSD), Casalecchio di Reno, Via Cimarosa, 5/2',
      "U.O. MEDICINA DELLO SPORT (SSD), Vergato, Via Dell'Ospedale, 1, Attività SOSPESA In attesa del medico",
      'U.O. MEDICINA DELLO SPORT (SSD), Castenaso, Via Marconi, 16 Attività SOSPESA In attesa del medico',
      'U.O. MEDICINA DELLO SPORT (SSD), Bentivoglio, Via Marconi, 35',
      'U.O. MEDICINA DELLO SPORT (SSD), Calderara, Via I° Maggio, 15',
      'U.O. MEDICINA DELLO SPORT (SSD), Molinella, Via Provinciale',
      'U.O. MEDICINA DELLO SPORT (SSD), San Pietro in Casale, Via Asia, 61',
      'U.O. AMM.VA DSP (SC), Bologna, Via Boldrini, 12',
      'U.O. AMM.VA DSP (SC), Bologna, Via Montebello 6',
      'U.O. AMM.VA DSP (SC), San Lazzaro di Savena, Via Seminario, 1',
      'U.O. AMM.VA DSP (SC), Casalecchio di Reno, Via Cimarosa, 5/2',
      'U.O. AMM.VA DSP (SC), Porretta Terme, Via Pier Capponi, 22',
      'U.O. AMM.VA DSP (SC), San Giorgio di Piano, Via Libertà, 45',
      'U.O. AMM.VA DSP (SC), San Giovanni in Persiceto, Circonvallazione Dante, 12d',
      'U.O. EPIDEM, PROM. DELLA SALUTE E COMUNICAZIONE DEL RISCHIO (SC), Bologna, Via Montebello 6',
      'U.O. EPIDEM, PROM. DELLA SALUTE E COMUNICAZIONE DEL RISCHIO (SC), San Lazzaro di Savena, Via Seminario, 1',
      'U.O. EPIDEM, PROM. DELLA SALUTE E COMUNICAZIONE DEL RISCHIO (SC), Porretta Terme, Via Pier Capponi, 22',
      'U.O. IGIENE ALIMENTI E NUTRIZIONE (SC), Bologna, Via Canali, 1 CAAB',
      'U.O. IGIENE ALIMENTI E NUTRIZIONE (SC), Bologna, Via Montebello 6',
      'U.O. IGIENE ALIMENTI E NUTRIZIONE (SC), San Lazzaro di Savena, Via Seminario, 1',
      'U.O. IGIENE ALIMENTI E NUTRIZIONE (SC), Casalecchio di Reno, Via Cimarosa, 5/2',
      'U.O. IGIENE ALIMENTI E NUTRIZIONE (SC), Porretta Terme, Via Pier Capponi, 22',
      'U.O. IGIENE ALIMENTI E NUTRIZIONE (SC), San Giorgio di Piano, Via Libertà, 45',
      'U.O. IGIENE ALIMENTI E NUTRIZIONE (SC), San Giovanni in Persiceto, Circonvallazione Dante, 12d',
      'U.O. IGIENE ALIMENTI E NUTRIZIONE (SC), Budrio, Via Mezzetti, 14',
      "U.O. IGIENE E SANITA' PUBBLICA DEGLI AMBIENTI DI VITA (SC), Bologna, Via Boldrini, 12",
      "U.O. IGIENE E SANITA' PUBBLICA DEGLI AMBIENTI DI VITA (SC), Casalecchio di Reno, Via Cimarosa, 5/2",
      "U.O. IGIENE E SANITA' PUBBLICA DEGLI AMBIENTI DI VITA (SC), Porretta Terme, Via Pier Capponi, 22",
      "U.O. IGIENE E SANITA' PUBBLICA DEGLI AMBIENTI DI VITA (SC), San Giorgio di Piano, Via Libertà, 45",
      "U.O. IGIENE E SANITA' PUBBLICA DEGLI AMBIENTI DI VITA (SC), San Giovanni in Persiceto, Circonvallazione Dante, 12d",
      "U.O. IGIENE E SANITA' PUBBLICA DEGLI AMBIENTI DI VITA (SC), Budrio, Via Mezzetti, 14",
      'U.O. IMPIANTISTICA ANTINFORTUNISTICA (SC), San Lazzaro di Savena, Via Seminario, 1',
      'U.O. PREVENZIONE DEL RISCHIO NELLE STRUTTURE SOCIO-SANITARIE DEL TERRITORIO (SSD), Bologna, Via Altura, 3',
      'U.O. PREVENZIONE DEL RISCHIO NELLE STRUTTURE SOCIO-SANITARIE DEL TERRITORIO (SSD), San Lazzaro di Savena, Via Seminario, 1',
      'U.O. PREVENZIONE DEL RISCHIO NELLE STRUTTURE SOCIO-SANITARIE DEL TERRITORIO (SSD), Casalecchio di Reno, Via Cimarosa, 5/2',
      'U.O. PREVENZIONE E SICUREZZA IN AMBIENTI DI LAVORO (SC), Bologna, Via Montebello 6',
      'U.O. PREVENZIONE E SICUREZZA IN AMBIENTI DI LAVORO (SC), San Lazzaro di Savena, Via Seminario, 1',
      'U.O. PREVENZIONE E SICUREZZA IN AMBIENTI DI LAVORO (SC), Casalecchio di Reno, Via Cimarosa, 5/2',
      'U.O. PREVENZIONE E SICUREZZA IN AMBIENTI DI LAVORO (SC), Porretta Terme, Via Pier Capponi, 22',
      'U.O. PREVENZIONE E SICUREZZA IN AMBIENTI DI LAVORO (SC), San Giorgio di Piano, Via Libertà, 45',
      'U.O. PREVENZIONE E SICUREZZA IN AMBIENTI DI LAVORO (SC), San Giovanni in Persiceto, Circonvallazione Dante, 12d',
      'U.O. PREVENZIONE E SICUREZZA IN AMBIENTI DI LAVORO (SC), Granarolo, Via San Donato, 74',
      'U.O. PREVENZIONE, SORVEGLIANZA E CONTROLLO DELLE MALATTIE INFETTIVE (SC), Bologna, Via Filippo Beroaldo 472',
      'U.O. PREVENZIONE, SORVEGLIANZA E CONTROLLO DELLE MALATTIE INFETTIVE (SC), Bologna, Via Montebello 6',
      'U.O. PREVENZIONE, SORVEGLIANZA E CONTROLLO DELLE MALATTIE INFETTIVE (SC), San Lazzaro di Savena, Via della Repubblica, 11',
      'U.O. PREVENZIONE, SORVEGLIANZA E CONTROLLO DELLE MALATTIE INFETTIVE (SC), Loiano, Via Roma, 8',
      'U.O. PREVENZIONE, SORVEGLIANZA E CONTROLLO DELLE MALATTIE INFETTIVE (SC), Pianoro, Via Risorgimento, 8',
      'U.O. PREVENZIONE, SORVEGLIANZA E CONTROLLO DELLE MALATTIE INFETTIVE (SC), Casalecchio di Reno, Via Cimarosa, 5/2',
      'U.O. PREVENZIONE, SORVEGLIANZA E CONTROLLO DELLE MALATTIE INFETTIVE (SC), Bazzano, Via De Martiri, 10 Osp. Dossetti',
      'U.O. PREVENZIONE, SORVEGLIANZA E CONTROLLO DELLE MALATTIE INFETTIVE (SC), Castiglione dei Pepoli, Via G. Sensi, 12',
      'U.O. PREVENZIONE, SORVEGLIANZA E CONTROLLO DELLE MALATTIE INFETTIVE (SC), Vado/Monzuno, Via Palmieri, 11',
      'U.O. PREVENZIONE, SORVEGLIANZA E CONTROLLO DELLE MALATTIE INFETTIVE (SC), Porretta Terme, Via Pier Capponi, 22',
      'U.O. PREVENZIONE, SORVEGLIANZA E CONTROLLO DELLE MALATTIE INFETTIVE (SC), Porretta Terme, Via Zagnoni, 3/5',
      "U.O. PREVENZIONE, SORVEGLIANZA E CONTROLLO DELLE MALATTIE INFETTIVE (SC), Vergato, Via Dell'Ospedale, 1",
      'U.O. PREVENZIONE, SORVEGLIANZA E CONTROLLO DELLE MALATTIE INFETTIVE (SC), San Giorgio di Piano, Via Libertà, 45',
      'U.O. PREVENZIONE, SORVEGLIANZA E CONTROLLO DELLE MALATTIE INFETTIVE (SC), Bentivoglio, Via Marconi, 35',
      'U.O. PREVENZIONE, SORVEGLIANZA E CONTROLLO DELLE MALATTIE INFETTIVE (SC), San Giovanni in Persiceto, Circonvallazione Dante, 12d',
      'U.O. PREVENZIONE, SORVEGLIANZA E CONTROLLO DELLE MALATTIE INFETTIVE (SC), Budrio, Via Benni, 44 (ospedale)',
      'U.O. VETERINARIA A e C (SC), Bologna, Via Boldrini, 2',
      'U.O. VETERINARIA A e C (SC), San Lazzaro di Savena, Via Seminario, 1',
      'U.O. VETERINARIA A e C (SC), Casalecchio di Reno, Via Cimarosa, 5/2',
      'U.O. VETERINARIA A e C (SC), Bazzano, Via De Martiri, 10 Osp. Dossetti',
      'U.O. VETERINARIA A e C (SC), Vergato, Via Fornaci, 343G',
      'U.O. VETERINARIA A e C (SC), Marzabotto, Via G. Matteotti, 10',
      'U.O. VETERINARIA A e C (SC), Anzola, Via XXV Aprile, 15',
      'U.O. VETERINARIA A e C (SC), San Giorgio di Piano, Via Libertà, 45',
      'U.O. VETERINARIA A e C (SC), San Giovanni in Persiceto, Circonvallazione Dante, 12d',
      'U.O. VETERINARIA A e C (SC), Budrio, Via Mezzetti, 14',
      'U.O. VETERINARIA B (SC), Bologna, Via Montebello 6',
      'U.O. VETERINARIA B (SC), San Lazzaro di Savena, Via Seminario, 1',
      'U.O. VETERINARIA B (SC), Casalecchio di Reno, Via Cimarosa, 5/2',
      'U.O. VETERINARIA B (SC), Vergato, Via Fornaci, 343G',
      'U.O. VETERINARIA B (SC), San Giorgio di Piano, Via Libertà, 45',
      'U.O. VETERINARIA B (SC), San Giovanni in Persiceto, Circonvallazione Dante, 12d',
      'UO GOVERNO DEI PERCORSI DI SCREENING, Bologna, Via Montebello 6',
      'UO GOVERNO DEI PERCORSI DI SCREENING, Vergato, Via Fornaci, 343G',
      'UO GOVERNO DEI PERCORSI DI SCREENING, San Giorgio di Piano, Via Libertà, 45',
      'UO GOVERNO DEI PERCORSI DI SCREENING, Budrio, Via Mezzetti, 14',
    ],
    uo: [],
  },
  'IRCCS Istituto Ortopedico Rizzoli': {
    uo: [
      'Day Surgery - Amb. Chirurgico',
      'Reparto Dozzinanti',
      'SC Anestesia e Terapia Intensiva posto operatoria e del dolore - Ambulatorio',
      'SC Anestesia e Terapia Intensiva posto operatoria e del dolore - Ambulatorio terapia antalgica',
      'SC Anestesia e Terapia Intensiva posto operatoria e del dolore - Reparto',
      'SC Chirurgia della Spalla e del Gomito - Ambulatorio',
      'SC Chirurgia della Spalla e del Gomito - Prericovero',
      'SC Chirurgia della Spalla e del Gomito - Reparto',
      'SC Chirurgia Ortopedica Ricostruttiva Tecniche Innovative - Ambulatorio',
      'SC Chirurgia Ortopedica Ricostruttiva Tecniche Innovative - Prericovero',
      'SC Chirurgia Ortopedica Ricostruttiva Tecniche Innovative - Reparto',
      'SC Chirurgia vertebrale - Ambulatorio',
      'SC Chirurgia vertebrale - Prericovero',
      'SC Chirurgia vertebrale - Reparto',
      'SC Clinica IV - Ortopedica - Ambulatorio',
      'SC Clinica IV - Ortopedica - Prericovero',
      'SC Clinica IV - Ortopedica - Reparto',
      'SC Clinica Ortopedica e Traumatologica I - Ambulatorio',
      'SC Clinica Ortopedica e Traumatologica I - Prericovero',
      'SC Clinica Ortopedica e Traumatologica I - Reparto',
      'SC Clinica Ortopedica e Traumatologica II - Ambulatorio',
      'SC Clinica Ortopedica e Traumatologica II - Prericovero',
      'SC Clinica Ortopedica e Traumatologica II - Reparto',
      'SC Clinica Ortopedica e Traumatologica III a prevalente indirizzo oncologico - Ambulatorio',
      'SC Clinica Ortopedica e Traumatologica III a prevalente indirizzo oncologico - Prericovero',
      'SC Clinica Ortopedica e Traumatologica III a prevalente indirizzo oncologico - Reparto',
      'SC Malattie Rare Scheletriche',
      'SC Medicina Fisica e Riabilitativa 1 - Ambulatorio',
      'SC Medicina Fisica e Riabilitativa 1 - Reparto',
      'SC Medicina Fisica e Riabilitativa 1 - Servizio',
      'SC Ortopedia pediatrica - Ambulatorio',
      'SC Ortopedia pediatrica - Ambulatorio ex Day Hospital',
      'SC Ortopedia pediatrica - Prericovero pediatrici',
      'SC Ortopedia pediatrica - Reparto',
      "SC Ortopedia-Traumatologia e Chirurgia protesica e dei reimpianti d'anca e di ginocchio - Ambulatorio",
      "SC Ortopedia-Traumatologia e Chirurgia protesica e dei reimpianti d'anca e di ginocchio - Prericovero",
      "SC Ortopedia-Traumatologia e Chirurgia protesica e dei reimpianti d'anca e di ginocchio - Reparto",
      "SC Osteoncologia, sarcomi dell'osso e dei tessuti molli, e terapie innovative - Ambulatorio",
      "SC Osteoncologia, sarcomi dell'osso e dei tessuti molli, e terapie innovative - DSA",
      "SC Osteoncologia, sarcomi dell'osso e dei tessuti molli, e terapie innovative - Reparto",
      'SC Radiologia Diagnostica e Interventistica',
      "SC Traumatologia e Ortopedia d'Urgenza",
      'SIMT-AMBO - Trasfusionale',
      'SSD Anatomia e Istologia Patologica',
      'SSD Chirurgia Generale e Toracica - Ambulatorio',
      'SSD Chirurgia Generale e Toracica - Prericovero',
      'SSD Chirurgia Generale e Toracica - Reparto',
      'SSD Medicina e Reumatologia',
      'SSD Pronto Soccorso',
      'SC Ortopedia Bentivoglio - Ambulatorio',
      'SC Ortopedia Bentivoglio - Prericovero',
      'SC Ortopedia Bentivoglio - Reparto',
      'Altro - Ambulatori provincia Bologna',
    ],
    structurePavilionAddress: [
      'Ospedale - Via Pupilli, 1',
      'Poliambulatorio - Via di Barbiano, 1/13',
      'Altra sede IOR provincia Bologna',
    ],
  },
  'AUSLBO Hospice': {
    uo: [],
    structurePavilionAddress: [
      'OSPEDALE MAGGIORE, LARGO BARTOLO NIGRISOLI 2, BOLOGNA',
      'OSPEDALE BELLARIA, VIA ALTURA3, BOLOGNA',
      'OSPEDALE BAZZANO, VIALE DEI MARTIRI 10/B, VALSAMOGGIA',
      'OSPEDALE BENTIVOGLIO, VIA MARCONI 35, BENTIVOGLIO',
      'OSPEDALE BUDRIO, VIA BENNI 44, BUDRIO',
      'OSPEDALE LOIANO, VIA SIMIANI 6, LOIANO',
      'OSPEDALE PORRETTA, VIA ZAGNONI 5, PORRETTA TERME',
      "OSPEDALE VERGATO, VIA DELL'OSPEDALE 1, VERGATO",
      'OSPEDALE SAN GIOVANNI, VIA ENZO PALMA 1, SAN GIOVANNI IN PERSICETO',
      'HOSPICE BELLARIA, PADIGLIONE TINOZZIVIA ALTURA 3 A, BOLOGNA',
      'HOSPICE BENTIVOGLIO, VIA MARCONI 43, BENTIVOGLIO',
      'HOSPICE CASALECCHIO, VIA DELLA RESISTENZA 38, CASALECCHIO DI RENO',
      'HOSPICE PEDIATRICO, VIA RIO POLO 3, BOLOGNA',
    ],
  },
  'IRCCS Azienda Ospedaliero-Universitaria Policlinico di S.Orsola': {
    uo: [
      'Cardio-pediatria nei reparti pediatrici (Programma dipartimentale)',
      'Angiologia e malattie della coagulazione',
      'Insufficienze cardiache e trapianti',
      'Anestesia e rianimazione ctv',
      "Cardiochirurgia pediatrica e dell'eta' evolutiva",
      'Cardiochirurgia',
      "Cardiologia pediatrica e dell'eta'evolutiva",
      'Cardiologia',
      'Patologia steno-ostruttiva delle arterie degli arti inferiori (Programma interaziendale)',
      'Chirurgia vascolare',
      'Medicina interna, malattie neurovascolari ed epatometaboliche',
      'Medicina interna cardiovascolare',
      'Pneumologia interventistica',
      'Pneumologia e terapia intensiva respiratoria',
      "Chirurgia a e d'urgenza",
      'Chirurgia toracica',
      "Governo dei percorsi riabilitativi dall'ospedale al territorio",
      'Geriatria acuti, ortogeriatria e centro disturbi cognitivi e demenze (CDCD)',
      'Geriatria acuti e continuità assistenziale',
      'Medicina fisica e riabilitazione',
      'Chirurgia laparoscopica malattie infiammatorie e neoplastiche del colon retto (Programma dipartimentale)',
      'Ecografia interventistica diagnostica e terapeutica (Programma dipartimentale)',
      "Chirurgia addominale nell'insufficienza d'organo terminale e nei pazienti con trapianto d'organo (Programma)",
      'Medicina interna e malattie immunoreumatologiche (Programma dipartimentale)',
      "Chirurgia metabolica e dell'obesita'",
      'Malattie infiammatorie croniche intestinali',
      'Patologia organica esofago-gastrica',
      "Chirurgia del tratto alimentare e dell'urgenza",
      'Chirurgia epatobiliare e dei trapianti',
      'Chirurgia del pancreas ed endocrina',
      'Endocrinologia, prevenzione e cura del diabete',
      'Gastroenterologia',
      'Medicina interna e fisiopatologia digestiva',
      'Medicina interna, malattie epatobiliari e immunoallergologiche',
      "Nutrizione clinica e metabolismo - centro regionale di riferimento per l'insufficienza intestinale cronica benigna",
      "Medicina interna per il trattamento delle gravi insufficienze d'organo",
      'Semeiotica medica',
      'Terapia intensiva post chirurgica e dei trapianti di organi addominali',
      'Radiologia addomino-pelvica diagnostica e interventistica',
      "Radiologia cardio-toraco-vascolare, oncoematologica, d'urgenza e dell'eta' pediatrica",
      'Dermatologia oncologica',
      'Macula e patologia vitreo retinica',
      'Chirurgia orale e maxillo facciale',
      'Chirurgia plastica',
      'Dermatologia',
      'Oftalmologia',
      'Otorinolaringoiatria e audiologia',
      'Andrologia',
      'Nefrologia, dialisi e trapianto - la manna',
      'Urologia',
      'Emolinfopatologia',
      'Malattie emorragiche congenite',
      'Oncologia medica Addarii',
      'Chirurgia senologica',
      'Ematologia',
      'Medicina nucleare',
      'Oncologia ginecologica',
      'Oncologia medica',
      'Radioterapia - morganti',
      'Trapianto e terapie cellulari in ematologia',
      'Nefrologia e dialisi pediatrica',
      'Anestesiologia e rianimazione generale e pediatrica',
      'Chirurgia pediatrica',
      'Genetica medica',
      'Ginecologia e fisiopatologia della riproduzione umana',
      'Neonatologia e terapia intensiva neonatale',
      'Oncoematologia pediatrica',
      "Ostetricia e medicina dell'eta' prenatale",
      'Pediatria',
      'Anestesiologia e T.I. polivalente',
      'Anestesiologia e terapia del dolore',
      "Medicina d'urgenza e pronto soccorso",
      'Malattie infettive',
      'Ortopedia e traumatologia',
      'Poliambulatorio',
      'Servizio sociale',
      'Governo Clinico e Qualità',
      'Direzione strategica',
      'Servizio di Piscologia Clinica Ospdeliera',
    ],
    structurePavilionAddress: [
      'PAD. 1 - Via Palagi, 9',
      'PAD. 2 - Via Palagi, 16',
      'PAD. 2 - POLIAMBULATORIO - Via Albertoni, 11/2',
      'PAD. 3 - Via Albertoni, 15',
      'PAD. 4 - Via Massarenti, 13',
      'PAD. 5 - Via Albertoni, 10',
      'PAD. 6 - Via Massarenti, 11',
      'PAD. 8 - Via Massarenti, 11',
      'PAD. 11 - Via Massarenti, 11',
      'PAD. 13 - Via Massarenti, 11',
      'PAD. 14 - Viale Ercolani, 4/3',
      'PAD. 15 - Viale Ercolani, 4/3',
      'PAD. 16 - Via Massarenti, 9',
      'PAD. 21 - Via Massarenti, 5',
      'PAD. 23 - Viale Ercolani, 4',
      'PAD. 24 - Via Massarenti, 5',
      'PAD. 25 - Viale Ercolani, 4',
      'PAD. 27 - Viale Ercolani, 4',
      'PAD. 28 - Viale Ercolani, 4',
      'PAD. 29 - Viale Ercolani, 4',
      'PAD. 30 - Via Albertoni, 10',
    ],
  },
  'AUSLBO Dipartimenti Ospedalieri': {
    uo: [],
    structurePavilionAddress: [
      'OSPEDALE MAGGIORE, LARGO BARTOLO NIGRISOLI 2, BOLOGNA',
      'OSPEDALE BELLARIA, VIA ALTURA3, BOLOGNA',
      'OSPEDALE BAZZANO, VIALE DEI MARTIRI 10/B, VALSAMOGGIA',
      'OSPEDALE BENTIVOGLIO, VIA MARCONI 35, BENTIVOGLIO',
      'OSPEDALE BUDRIO, VIA BENNI 44, BUDRIO',
      'OSPEDALE LOIANO, VIA SIMIANI 6, LOIANO',
      'OSPEDALE PORRETTA, VIA ZAGNONI 5, PORRETTA TERME',
      "OSPEDALE VERGATO, VIA DELL'OSPEDALE 1, VERGATO",
      'OSPEDALE SAN GIOVANNI, VIA ENZO PALMA 1, SAN GIOVANNI IN PERSICETO',
      'HOSPICE BELLARIA, PADIGLIONE TINOZZIVIA ALTURA 3 A, BOLOGNA',
      'HOSPICE BENTIVOGLIO, VIA MARCONI 43, BENTIVOGLIO',
      'HOSPICE CASALECCHIO, VIA DELLA RESISTENZA 38, CASALECCHIO DI RENO',
      'HOSPICE PEDIATRICO, VIA RIO POLO 3, BOLOGNA',
    ],
  },
};
